name: Upload Python Package
on:
  push:
    branches:
      - main
env:
  dothttpversion: v0.0.42a5
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.5"
      - name: Install dependencies
        run: |
          git clone https://github.com/cedric05/dothttp.git dothttp
          cd dothttp
          git fetch --all
          git checkout ${{ env.dothttpversion }}
          python -m pip install -r all_requirements.txt
          python -m pip install python-magic
          python -m unittest
          git apply ../*.patch
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd dothttp
          python setup.py sdist bdist_wheel
          python setup.py sdist sdist
          ls -alh dist
          twine upload dist/*
